### ISSUE TITLE
关于JX.base中的注释

### ISSUE THREAD

**Issue by Singularity-zju** [AlloyTeam/JX#2]
pass方法的注释   

 /**
     \* 给函数传入参数并执行
     \* 
     \* @memberOf Jx.prototype
     \* @param {Mixed} args 参数列表
     \* @return {Mixed} 返回函数执行结果
     \* 
     \* @example
     \* Jx().$package(function(J){
     \*     // 将"a"、"b"两个字符串传入funcA函数并执行
     \*     funcA.pass("a","b");
     \* };
     */

对用法有所疑问
是否应该为

```
  Jx().$package(function(J){
    J.pass(funcA,"a","b")();     
 });
```

或者     

```
 Jx().$package(function(J){
     var newF = J.pass(funcA,"a","b");
     newF("c"); 
 })
```

**Comment by yuanyan** [comment]
```
  Jx().$package(function(J){
     var newF = J.pass(funcA,"a","b");
     newF("c"); 
 })
```

 为正确调用方式，pass返回绑定后的函数
